### ISSUE TITLE
Make #named_tags available to Logger instance

### ISSUE THREAD

**Issue by allcentury** [rocketjob/semantic_logger#119]
### Environment

Provide at least:
* Ruby Version.  2.4.3
* Semantic Logger Version. 4.2.0
* Application/framework names and versions (e.g. Rails, Sinatra, Puma, etc.). Rails
* Rails Semantic Logger Version, if applicable. 4.2.1
* Rails configuration. Only need the settings related to Rails Semantic Logger and Semantic Logger.
```ruby
 STDOUT.sync = true
 config.rails_semantic_logger.add_file_appender = false
 config.rails_semantic_logger.format = :color
 config.semantic_logger.add_appender(
   io: STDOUT,
   application: Rails.application.class.name,
   level: config.log_level,
   formatter: config.rails_semantic_logger.format,
 )
```
* Full Stack Trace, if an exception is being raised.

Note:
* If the issue is with extensions to Rails to make it use Semantic Logger, please report the issue at [Rails Semantic Logger](https://github.com/rocketjob/rails_semantic_logger/issues).
* All appender issues should be reported here.

### Expected Behavior

Rails.logger returns an instance of `SemanticLogger::Logger` but that class has no access to `named_tags`, only `SemanticLogger` has access to it.

### Actual Behavior

`Rails.logger.named_tags` returns a no method error.

**Comment by reidmorrison** [comment]
Thank you for the pull request
