### ISSUE TITLE
Please provide straightforward set up instructions for logging newbies.

### ISSUE THREAD

**Issue by joshk6** [rocketjob/semantic_logger#121]
The product looks like it will be very useful, but after an hour of fiddling around in Rails 5.2 I have not succeeded in getting the logger to print anything on the console.  E.g. do I have to set the logging level in each class, am I supposed to delete the logging configurations options development.rb etc etc.  There are lots of helpful code samples, but not at all clear where some of that code is supposed to go.

**Comment by workgena** [comment]
From README:

> When running Rails, use rails_semantic_logger instead of Semantic Logger directly since it will automatically replace the Rails default logger with Semantic Logger.

Did you tried [rails_semantic_logger](https://github.com/rocketjob/rails_semantic_logger)? It should "just work" without any manual settings.

Gemfile:

```ruby

**Comment by reidmorrison** [comment]
Documentation: https://rocketjob.github.io/semantic_logger/rails.html
