### ISSUE TITLE
Proposal for JRuby changes

### ISSUE THREAD

**Issue by dgolombek** [rocketjob/semantic_logger#122]
I wanted to get feedback about a few changes I'm thinking about that are primarily JRuby focused, but might be of general interest:

1) Remove PID from Log#process_info on JRuby. It's really rare to fork with JRuby, due to high overhead of doing so and the prevalence of threads. So this is wasted log line space. Currently there's no clean way to achieve this, since the Formatter is calling Log.process_info.

2) Allow callers to provide a formatter for Exceptions. When JRuby deploys are packaged into a jar/war, stack trace log lines can become REALLY long, since they include the full path of that jar/war file. I don't have a firm design in place for this yet, wanted to get feedback first.

3) Allow configuring of SemanticLogger::Formatters::Base::PRECISION. I sometimes don't want 6 digit precision (usually due to working with logger processing tools that can't handle it), BUT I want ISO_8601 formatting. Without this, getting the time into UTC then formatted isn't doable (I think). I think Log#duration_to_s would keep using the default precision for simplicity.

I'm happy to implement these, just wanted to run them by you and get feedback, particularly on the second idea.

Thanks
Dave

**Comment by reidmorrison** [comment]
Creating a custom formatter should allow all of the above to be achieved, if not we need to fix the customization mechanism: http://rocketjob.github.io/semantic_logger/customize.html

**Comment by dgolombek** [comment]
Yeah, that was definitely the goal here -- as noted, the precision part couldn't be achieved easily before. Thanks for merging that in. 

For the exception formatting, the challenge is trying to avoid duplicating code from SemanticLogger::Log#backtrace_to_s. What I was thinking about was adding a Formatter#format_backtrace method, which backtrace_to_s then invoked for each exception's backtrace in the list of exception. That would let users just override that piece, rather than overriding all of Formatter#exception and Log#backtrace_to_s .
