### ISSUE TITLE
Does SemanticLogger.reopen support restarting of SemanticLogger::Appender::Async and SemanticLogger::Appender::AsyncBatch threads?

### ISSUE THREAD

**Issue by cyril-s** [rocketjob/semantic_logger#129]
### Environment
ruby 2.3.3
semantic_logger 4.3.0
rails 5.2

### Description
Hi, I noticed that call to `SemanticLogger.reopen` from unicorn's `after_fork` block (as suggested in [docs](http://rocketjob.github.io/semantic_logger/forking.html)) does not restart AsyncBatch Elasticsearch appender configured like this:
```ruby
SemanticLogger.add_appender(
  appender: :elasticsearch,
  url: "http://localhost:9200",
  batch_size: 10,
  index: myapp
)
```
It seems that in my case call to reopen just creates new Elasticsearch client:
```ruby
# lib/semantic_logger/semantic_logger.rb
def self.reopen
  @appenders.each { |appender| appender.reopen if appender.respond_to?(:reopen) }
  # After a fork the appender thread is not running, start it if it is not running.
  SemanticLogger::Processor.start
end
```
```ruby
# lib/semantic_logger/appender/elasticsearch.rb
def reopen
  @client = ::Elasticsearch::Client.new(@elasticsearch_args)
end
```
And similar behavior appears to be in other appenders.

Is such a case even supported?

**Comment by reidmorrison** [comment]
Yes, it sounds like Async and AsyncBatch need to implement `#reopen` and then make sure they call `#reopen` in turn to any child appenders.

**Comment by reidmorrison** [comment]
@cyril-s I made a change in master to forward the `#reopen` to the child appender when using Async, can you give master a try and let me know if it works?
https://github.com/rocketjob/semantic_logger/commit/d9cda0d762d88e6c92de1432f4a36464cf0ce294

Once this is fixed I will publish gem v4.4.

**Comment by cyril-s** [comment]
@reidmorrison tested both Async and AsyncBatch queues and they seem to work fine

**Comment by reidmorrison** [comment]
Thank you, gem v4.4.0 has been published with this fix.
