### ISSUE TITLE
Appenders#close always raises and logs NameError: undefined local variable or method `appenders' for #<SemanticLogger::Appenders:0x...>

### ISSUE THREAD

**Issue by marco-nicola** [rocketjob/semantic_logger#133]
### Environment

* Ruby Version: `ruby-2.6.1` installed with `rvm` &rarr; `ruby 2.6.1p33 (2019-01-30 revision 66950) [x86_64-linux]`
* Semantic Logger Version: `4.4.0`
* Not using any framework, nor Rails Semantic Logger
* Full Stack Trace (please note that the error's stack trace is logged, but the exception itself is not re-raised):
```
SemanticLogger::Appenders -- Failed to close appender: #<SemanticLogger::Appender::File:0x0000560cd3a82498 @log=#<IO:<STDOUT>>, @formatter=#<SemanticLogger::Formatters::Color:0x0000560cd3adf670 @ai_options={:multiline=>false}, @color_map=#<SemanticLogger::Formatters::Color::ColorMap:0x0000560cd3adf620 @trace="\e[35m", @debug="\e[32m", @info="\e[36m", @warn="\e[1m", @error="\e[31m", @fatal="\e[31m", @bold="\e[1m", @clear="\e[0m">, @time_format="%Y-%m-%d %H:%M:%S.%6N", @log_host=false, @log_application=false, @precision=6, @color="\e[36m", @log=#<SemanticLogger::Log:0x0000560cd3afac40 @level=:info, @thread_name="47306542340460", @name="Foo", @time=2019-02-18 22:27:39 +0100, @tags=[], @named_tags={}, @level_index=2, @message="The logger just works as expected here.">, @logger=#<SemanticLogger::Appender::File:0x0000560cd3a82498 ...>>, @application=nil, @host=nil, @metrics=false, @filter=nil, @name="SemanticLogger::Appender::File", @level_index=nil, @level=nil> -- Exception: NameError: undefined local variable or method `appenders' for #<SemanticLogger::Appenders:0x0000560cd3a82768>
Did you mean?  appender
               append
/home/foo/.rvm/gems/ruby-2.6.1/gems/semantic_logger-4.4.0/lib/semantic_logger/appenders.rb:46:in `block in close'
/home/foo/.rvm/gems/ruby-2.6.1/gems/semantic_logger-4.4.0/lib/semantic_logger/appenders.rb:41:in `each'
/home/foo/.rvm/gems/ruby-2.6.1/gems/semantic_logger-4.4.0/lib/semantic_logger/appenders.rb:41:in `close'
/home/foo/.rvm/gems/ruby-2.6.1/gems/semantic_logger-4.4.0/lib/semantic_logger/appender/async.rb:171:in `process_message'
/home/foo/.rvm/gems/ruby-2.6.1/gems/semantic_logger-4.4.0/lib/semantic_logger/appender/async.rb:158:in `process_messages'
/home/foo/.rvm/gems/ruby-2.6.1/gems/semantic_logger-4.4.0/lib/semantic_logger/appender/async.rb:119:in `process'
/home/foo/.rvm/gems/ruby-2.6.1/gems/semantic_logger-4.4.0/lib/semantic_logger/appender/async.rb:75:in `block in thread'
```

### Scenario and example script

Suppose I'm creating a simple stand-alone application which uses `semantic_logger` in a straightforward way, just to nicely log some messages.

The app starts requiring `semantic_logger`, adding at least one appender, and creating at least one stand-alone logger instance; this instance is then simply used for a while to log various messages.

Eventually, the app execution reaches a point from where it does not need those logging features anymore, so it politely calls `SemanticLogger.close` to flush everything and to (possibly) free some resources; then it just continues with other operations.

Here is a minimal example:

```ruby
# Requirements:
# - Ruby version `2.6.0`
# - 'semantic_logger' gem version '4.4.0'
#   (`gem install semantic_logger -v 4.4.0` on command-line,
#    or `gem 'semantic_logger', '4.4.0'` in your Gemfile for Bundler)

require 'semantic_logger'

puts 'My program starts.'

SemanticLogger.default_level = :trace
SemanticLogger.add_appender(io: STDOUT, formatter: :color)

logger = SemanticLogger['Foo']
logger.info "The logger just works as expected here."

# ... do some stuff and use 'logger' ...

SemanticLogger.close

# ... do some other stuff, without logging anything anymore...

puts 'My program ends.
```

An additional important assumption for this example is that I don't expect any external error interfering with the logger's operations (e.g. no I/O errors or similar).

### Expected Behavior

When `SemanticLogger.close` is invoked, it should successfully _"close all appenders and flush any outstanding messages"_ (as documented). I don't expect any error to be raised and I also don't expect any further message to be logged out (since I'm just closing all appenders).

Well, to be extremely precise, it would still be OK if during the `close`-ing process I would get a couple of `trace`-level messages, such as `Closing appender: ...` or `All appenders closed and removed from appender list`, but that should be _really_ all I would expect at most. This point is however not particularly significant for the present issue.

In practice, this is the program output that I would expect: 

```
My program starts.
2019-02-18 22:34:51.766157 I [11355:47304954779980] Foo -- The logger just works as expected here.
My program ends.
```

### Actual Behavior

The call to `SemanticLogger.close` triggers a chain of events (described later on in more details) which eventually reach the method `SemanticLogger::Appenders#close`: the implementation of this method _always_ raises a `NameError` exception. The error is however immediately rescued, it is logged out as an error message, but not re-raised, so that my program continues and reaches its end without errors.

Here is the actual output:

```
My program starts.
2019-02-18 22:38:15.908439 I [11971:46986783922540] Foo -- The logger just works as expected here.
2019-02-18 22:38:15.908663 E [11971:SemanticLogger::Appenders] SemanticLogger::Appenders -- Failed to close appender: #<SemanticLogger::Appender::File:0x00005577ed801cd0 @log=#<IO:<STDOUT>>, @formatter=#<SemanticLogger::Formatters::Color:0x00005577ed859b60 @ai_options={:multiline=>false}, @color_map=#<SemanticLogger::Formatters::Color::ColorMap:0x00005577ed859ac0 @trace="\e[35m", @debug="\e[32m", @info="\e[36m", @warn="\e[1m", @error="\e[31m", @fatal="\e[31m", @bold="\e[1m", @clear="\e[0m">, @time_format="%Y-%m-%d %H:%M:%S.%6N", @log_host=false, @log_application=false, @precision=6, @color="\e[36m", @log=#<SemanticLogger::Log:0x00005577ed564a18 @level=:info, @thread_name="46986783922540", @name="Foo", @time=2019-02-18 22:38:15 +0100, @tags=[], @named_tags={}, @level_index=2, @message="The logger just works as expected here.">, @logger=#<SemanticLogger::Appender::File:0x00005577ed801cd0 ...>>, @application=nil, @host=nil, @metrics=false, @filter=nil, @name="SemanticLogger::Appender::File", @level_index=nil, @level=nil> -- Exception: NameError: undefined local variable or method `appenders' for #<SemanticLogger::Appenders:0x00005577ed801fa0>
Did you mean?  appender
               append
/home/foo/.rvm/gems/ruby-2.6.1/gems/semantic_logger-4.4.0/lib/semantic_logger/appenders.rb:46:in `block in close'
/home/foo/.rvm/gems/ruby-2.6.1/gems/semantic_logger-4.4.0/lib/semantic_logger/appenders.rb:41:in `each'
/home/foo/.rvm/gems/ruby-2.6.1/gems/semantic_logger-4.4.0/lib/semantic_logger/appenders.rb:41:in `close'
/home/foo/.rvm/gems/ruby-2.6.1/gems/semantic_logger-4.4.0/lib/semantic_logger/appender/async.rb:171:in `process_message'
/home/foo/.rvm/gems/ruby-2.6.1/gems/semantic_logger-4.4.0/lib/semantic_logger/appender/async.rb:158:in `process_messages'
/home/foo/.rvm/gems/ruby-2.6.1/gems/semantic_logger-4.4.0/lib/semantic_logger/appender/async.rb:119:in `process'
/home/foo/.rvm/gems/ruby-2.6.1/gems/semantic_logger-4.4.0/lib/semantic_logger/appender/async.rb:75:in `block in thread'
My program ends.
```

#### Detailed Behavior

When [`SemanticLogger.close`](https://github.com/rocketjob/semantic_logger/blob/859fb1c720dfebc1519f62492ed168ce90a8711e/lib/semantic_logger/semantic_logger.rb#L182) is invoked, in its turn it just invokes `SemanticLogger::Logger.processor.close`; this correctly submits a `close` asynchronous command, which is then handled (indeed, asynchronously) by `SemanticLogger::Processor` (being it a subclass of `SemanticLogger::Appender::Async`).

`SemanticLogger::Appender::Async#process_message`, still correctly, invokes [`appender.close`](https://github.com/rocketjob/semantic_logger/blob/v4.4.0/lib/semantic_logger/appender/async.rb#L171): that `appender` is an `attr_reader` whose value is an instance of `SemanticLogger::Appenders`. Thus, this is actually an invocation to [`SemanticLogger::Appenders#close`](https://github.com/rocketjob/semantic_logger/blob/v4.4.0/lib/semantic_logger/appenders.rb#L40).

Being the class a (concurrent) array itself, its `close` method [loops](https://github.com/rocketjob/semantic_logger/blob/v4.4.0/lib/semantic_logger/appenders.rb#L41) through each of its own elements, so that each of them is [flushed](https://github.com/rocketjob/semantic_logger/blob/v4.4.0/lib/semantic_logger/appenders.rb#L44), [closed](https://github.com/rocketjob/semantic_logger/blob/v4.4.0/lib/semantic_logger/appenders.rb#L45), and then "in theory" removed from the list (i.e. again, the array-instance in itself).

That very last passage results however being incorrect. The involved line of code is [`appenders.delete(appender)`](https://github.com/rocketjob/semantic_logger/blob/v4.4.0/lib/semantic_logger/appenders.rb#L46): it tries to delete the `appender` variable from `appenders`, however the latter is _something_ that simply does not exists in the current scope (it's not a method, nor an attribute, nor a variable).

At the end, the appender is correctly closed and flushed, however its removal from the list fails, clearly raising a `NameError`. As we already noticed, the exception is immediately [rescued](https://github.com/rocketjob/semantic_logger/blob/v4.4.0/lib/semantic_logger/appenders.rb#L63), logged as an error message to the instance's logger, but not re-raised. So, no apparent major damage is caused to my application, however that error is still logged out as a critical message; moreover, in any case the `Appenders` instance is probably in a sort of "unclean" state (whose possible bad consequences I had no occasion to evaluate).

### Possible causes

It seems to me that the issue is a consequence of this commit here: https://github.com/rocketjob/semantic_logger/commit/859fb1c720dfebc1519f62492ed168ce90a8711e#diff-cb2c926a04345fa22a7a4b4311eee2c9 (`Break out Appenders and Levels into separate files`)

Just with very minimal variations, the new [`SemanticLogger::Appenders#close`](https://github.com/rocketjob/semantic_logger/commit/859fb1c720dfebc1519f62492ed168ce90a8711e#diff-cb2c926a04345fa22a7a4b4311eee2c9R40) method seems to come directly from the older method [`SemanticLogger::Processor::close`](https://github.com/rocketjob/semantic_logger/commit/859fb1c720dfebc1519f62492ed168ce90a8711e#diff-b7adcd1913e3b5ec95ce946bbca15772L73). The _old_ method was looping through (and deleting from) the `appenders` attr_reader (which was simply initialized as `@appenders   = Appenders.new`). After the refactoring, an instance of `Appenders` now operates directly within itself: in fact it loops throught all the appenders simply invoking `each` on itself; however, when each appender is deleted, the "old" `appenders` attribute is still used in the new code... but it's not there anymore, since it has now become simply (it)`self`.

That looks just like the typical average copy-paste leftover :sweat_smile: 

### Pull Request

According to my understanding of the code, I'm going to first suggest the least invasive little fix, simply correcting the faulty line of code, that is, performing the `delete` on the class instance itself.

I'll write here (or in a next message) the link to the Pull Request that I'm going to create.
EDIT: https://github.com/rocketjob/semantic_logger/pull/134

However, there may be more... just continue reading.

### Additional considerations (and maybe another related bug)

This bug allowed me to spot a couple of related issues.

First of all, I think it would be nice and useful to include some simple unit test cases for some (...all?) methods of the `Appenders` class, including that rascal `#close` method.

But, most important, I have the impression that - even after a simple fix - the `Appender#close` method is still not acting as it is supposed to do, in fact carrying on a bug already present in the older version of `SemanticLogger::Processor::close`.

Beware that maybe I'm missing something obvious - sorry for the false alarm in that case!

Here is the problem: in the implementation of `Appender#close`, the `each` loop is implicitly performed on `self`, that is a subclass of `Concurrent::Array`. Then, _inside_ the block of the loop, the current element `appender` is deleted from the array itself. Now, this deleting-while-looping thing is not only usually considered an anti-pattern, but it often leads to undesired results.

Here is a quick example:

```ruby
# Using ruby `2.6.1` and the gem `concurrent-ruby` version `1.1.4`

require 'concurrent'

arr = Concurrent::Array.new
arr << :a
arr << :b
arr << :c
arr << :d

arr.each { |item| arr.delete(item) }

p arr # => [:b, :d]
```

Unless keeping `b` and `d` was _exactly_ the desired behavior, this code is clearly not deleting all elements! If otherwise that was _really_ the desired behavior, I would still complain that it mostly looks like a sort of obfuscated code, masked as a kind bug, which would definitely deserve to be carefully documented (if not refactored into some more explicit and obvious code).

Anyway, I purposely do not try to fix this possible bug, nor I add new tests, since I would first like to hear the opinion of the Gem's authors and main maintainers about both things.

As said, the PR will follow shortly...

**Comment by reidmorrison** [comment]
Fix published in latest gem version. Thank you for the PR
