### ISSUE TITLE
Simpler syntax

### ISSUE THREAD

**Issue by cup** [rocketjob/semantic_logger#135]
It seems this is the simplest syntax:

~~~rb
require 'semantic_logger'
SemanticLogger.add_appender(io: STDERR)
q = SemanticLogger['']
q.warn('abcde')
~~~

compare with some Python options:

~~~py
import logging
logging.warning('abcde')
~~~

~~~py
import colorlog
colorlog.warning('abcde')
~~~

~~~py
from logzero import logger
logger.warning('abcde')
~~~

**Comment by reidmorrison** [comment]
`Chalk and Cheese`

Semantic Logger is designed to be included into every class and to support multiple concurrent  appenders, which may or may not include stderr or stdout.
