### ISSUE TITLE
Add synchronous processor support (incorrect log lines are untestable, and log output is interleaved with pry prompt)

### ISSUE THREAD

**Issue by rgalanakis** [rocketjob/semantic_logger#137]
### Environment

Ruby 2.6, Semantic Logger 4.5, Pry

### Expected Behavior

Logging from a console (pry, irb) should finish writing the logs emitted from the last command to the terminal/tty, so it does not interleave with the prompt text.

### Actual Behavior

When I log to the console with Pry, the log output is written potentially after Pry has set up the prompt. I believe this is because the log processing happens asynchronously. `STDOUT.sync = true` has been set.

See this example, where we log, and then the prompt (line `[7]`) is on a clean line. Then we log again, and the prompt (line `[8]`) has log output on its line.

```ruby
[6] pry(main)> Lithic.logger.info 'hello', foo: 'bar'
=> true
2019-08-07 15:37:37.072052 I [98058:70198828928620] Lithic -- hello -- { :foo => "bar" }
[7] pry(main)> Lithic.logger.info 'hello', foo: 'bar'
=> true
[8] pry(main)> 2019-08-07 15:37:38.618054 I [98058:70198828928620] Lithic -- hello -- { :foo => "bar" }
```

- Note this seems to happen with irb as well.
- It does not happen with the standard logger logging to stdout (`Logger.new(STDOUT).warn("hi")`)

This is quite frustrating behavior when working in a console and I'd love to see a way to write logs synchronously to avoid the interleaving.

### Pull Request

I wasn't sure how to approach changing this, or if it's even desirable (I think it is). I am happy to make the change if so. I was thinking that maybe if a tty is connected we always flush the queue after each logging, or initialize the logger differently, etc. Or maybe sniff some other cases (if the `io` is a stream with `sync=true`, etc).

**Comment by rgalanakis** [comment]
Note that this also leads to incorrect call usages not being hit during tests. Ie:

```ruby
begin
  raise IOError
rescue IOError => e
  logger.error("failed_thing", e, key: 'value')
end
```

This is invalid, it needs to be something like: `logger.error('failed_thing', exception: e, key: 'value')`, but it's only hit during log write time (`Exception: NoMethodError: undefined method `message' for #<Hash:0x00007fd0698ca2f8>` in `formatters/default.rb:59`).

**Comment by reidmorrison** [comment]
A key design principle with Semantic Logger is for all logging to be performed asynchronously. 
Synchronous logging slows down program execution while it logs data to the various appenders.
I don’t see how you can change such a key fundamental design principle.
I have redirected logging output to the console in production and have not seen the issues you describe, but there again we run JRuby which does not have the GIL and we don’t run pry.

**Comment by rgalanakis** [comment]
As per the second comment, this is not limited to Pry, or MRuby- in fact it leads to untestable logging code that will fail at runtime but not in a way that can be detected during tests. This, much more than the interleaved output, seems legitimately bad (and in fact I lost much time trying to understand what was going on when I saw it). But the interleaved output is really annoying too.

If support for synchronous output/flushing could be done explicitly (not implicitly as I suggested), and with minimal invasion of existing code, would it be added? It's not a matter of changing a key fundamental design principle- I agree with you about why logging should be asynchronous- it's about improving usability and ergonomics by using synchronous logging in specific desirable cases.

**Comment by reidmorrison** [comment]
We actually do test log messages especially ones that submit metrics. There is a mock logger that is used to test Semantic Logger itself. Essentially replace the logger instance on the tested class with the mock logger directly and verify it’s logged contents afterwards.
Making the mock logger available in a simple way for tests would make a good Pull Request for anyone up to the task?

**Comment by reidmorrison** [comment]
If this is a feature you want you could make the processor configurable:
https://github.com/rocketjob/semantic_logger/blob/master/lib/semantic_logger/logger.rb#L23

Currently the processor inherits from `Appender::Async`:
https://github.com/rocketjob/semantic_logger/blob/master/lib/semantic_logger/processor.rb#L3

By creating a configuration option you could make it create the appenders instance directly and bypass creating the processor altogether:
https://github.com/rocketjob/semantic_logger/blob/master/lib/semantic_logger/processor.rb#L26

I.e. Replace the processor instance internally directly with `Appenders.new`

If you have any questions about making the code changes and submitting the pull request to make it configurable let me know.

**Comment by rgalanakis** [comment]
Thank you for that change @reidmorrison 🤗
