### ISSUE TITLE
Upgrading to BugSnag v6 causes an endless loop

### ISSUE THREAD

**Issue by AlexanderMint** [rocketjob/semantic_logger#150]
### Code

``` ruby
require 'bugsnag'
require 'semantic_logger'

Bugsnag.configure do |config|
  config.api_key = '<YOUR_TOKEN>'
end

SemanticLogger.add_appender(appender: :bugsnag, level: :warn)
# it's not obligatory
SemanticLogger.add_appender(io: STDOUT, formatter: :color)

SemanticLogger['MyClass'].warn 'test'
```

### Result

```
2020-02-13 11:07:59.230502 W [9828:SemanticLogger::Appenders] SemanticLogger::Appender::Bugsnag -- [Bugsnag] -- Adding metadata/severity using a hash is no longer supported, please use block syntax instead
2020-02-13 11:07:59.232610 I [9828:SemanticLogger::Appenders] SemanticLogger::Appender::Bugsnag -- [Bugsnag] -- Notifying https://notify.bugsnag.com of RuntimeError
.......
```

There will be no errors if you specify for example log level error, but there are warnings in my code

### Expected Behavior

One error is sent to bugsnag

### Actual Behavior

Endless warning loop.

### Pull Request

https://github.com/rocketjob/semantic_logger/pull/149

**Comment by reidmorrison** [comment]
It is not an endless loop, it is just Bugsnag logging the warning with every call. They changed the API and then added the warning without any documentation that I could find on how to pass the arguments now.
Maybe you can find an example on what the new api is supposed to look like?
Also there does not appear to be way to know as of which version of Bugsnag this new api was available.
We are staying with Bugsnag v5 until someone can figure out what Bugsnag now needs.

**Comment by AlexanderMint** [comment]
@reidmorrison I am not familiar with the bugsnag API and do not follow it. Unfortunately, I can’t help you.

**Comment by reidmorrison** [comment]
I still want to upgrade our Bugsnag installation, so will have to cross this bridge soon.
