### ISSUE TITLE
Site typo

### ISSUE THREAD

**Issue by Roko131** [rocketjob/semantic_logger#158]
Wasn't sure where to add it, hope it's ok.

https://logger.rocketjob.io/rails.html
at _Log file name and line number_ section:

...feature can be used in production, but `use care` since setting the level too low will slow down the application...

should be:
...feature can be used in production, but `use with care` since setting the level too low will slow down the application...

Also:

https://logger.rocketjob.io/api.html

A logger instance should be created for every class so that `it’s` log entries can be uniquely identified from logging entries from other classes.

A logger instance should be created for every class so that `its` log entries can be uniquely identified from logging entries from other classes.

Another one:
https://logger.rocketjob.io/filtering.html

Give Resque its own logger with the custom filter qpplied to reduce `it's` verbosity

Give Resque its own logger with the custom filter qpplied to reduce `its` verbosity

**Comment by reidmorrison** [comment]
Thank you for the documentation fixes, they have been applied.
