### ISSUE TITLE
deprecation warning while using Elasticsearch-7.8.0

### ISSUE THREAD

**Issue by Fivell** [rocketjob/semantic_logger#167]
### Environment

* Ruby Version `2.5.5`
* Semantic Logger Version `4.7.4`
* Application/framework names and versions `Rails`
```
SemanticLogger.add_appender(
        appender: :elasticsearch,
        hosts: Rails.configuration.semantic_logger.dig(:elasticsearch, :hosts),
        batch_size: 10,
        retry_on_failure: true,
        type: '_doc',
        index: Rails.configuration.semantic_logger.dig(:elasticsearch, :index)
      )
      SemanticLogger.application = Rails.configuration.semantic_logger.dig(:elasticsearch, :index)

```

### Expected Behavior

* no warning in logs

### Actual Behavior

Warning: 299 Elasticsearch-7.8.0-757314695644ea9a1dc2fecd26d1a43856725e65 "[types removal] Specifying types in bulk requests is deprecated."

**Comment by Fivell** [comment]
specifying `type: nil` fixes issue

**Comment by shaunbugler** [comment]
It should be noted that from [Elastic 8.X](https://www.elastic.co/guide/en/elasticsearch/reference/7.17/removal-of-types.html) mapping types have been removed. While your fix hides this, semantic_logger should not set the type by default going forward
