### ISSUE TITLE
3.3 gives error when used with rails

### ISSUE THREAD

**Issue by timuckun** [rocketjob/semantic_logger#23]
I filed a ticket over at the rails_semantic_logger repo 

https://github.com/rocketjob/rails_semantic_logger/issues/14

It gives an error complaining the development.log file does not exist or doesn't have permissions. The error occurs even if the file exists and does have to correct permissions (0666)

**Comment by reidmorrison** [comment]
No need to open a second ticket here. The first is in the correct place and is sufficient.
