### ISSUE TITLE
Documentation for Logentries

### ISSUE THREAD

**Issue by zach-taylor** [rocketjob/semantic_logger#25]
Hello!

Thanks for all your work on Semantic Logger, it's by far the best logging library for Ruby. The TCP logging feature is working great. I was able to get it working with logentries.com by doing the following:

```ruby
module Example
  module Formatters
    class Logentries < SemanticLogger::Formatters::Json
      def call(log, logger)
        "#{LOG_ENTRIES_TOKEN} #{super(log, logger)}"
      end
    end
  end
end


formatter = Example::Formatters::Logentries.new
SemanticLogger.add_appender(appender: :tcp, server: 'api.logentries.com:20000', ssl: true, formatter: formatter)
```

which uses the TCP method documented here: https://logentries.com/doc/input-token/

I thought you may want to add this information to the Semantic Logger documentation.

Thanks!

**Comment by reidmorrison** [comment]
Thank you for the feedback, I added the information to the documentation.
