### ISSUE TITLE
Can you load this with a default tag or context?

### ISSUE THREAD

**Issue by magicalbanana** [rocketjob/semantic_logger#27]
e.g
```ruby
ActiveSupport::TaggedLogging.new(Syslog::Logger.new('foo'))
````

How would you initialize `SemanticLogger` to behave like this?

**Comment by reidmorrison** [comment]
Can you describe what you are trying to do?
Tagged logging is built into Semantic Logger, so it should not be used with `ActiveSupport::TaggedLogging`

**Comment by magicalbanana** [comment]
Basically, I am trying to replace Rails logger without using the gem because there's a lot of config baked into the gem already.

Because at an organization I work at, we don't even log to file but directly to syslog. Is it possible to only have one appender?

**Comment by reidmorrison** [comment]
We have users of the Rails Semantic Logger gem that only send logs to a centralized logging service. I.e. Without any local file logging.

There is a config option to turn off the local file logger with Rails Semantic Logger. In application.rb:
~~~ruby
config.rails_semantic_logger.add_file_appender = false
~~~

Then just add the Syslog appender in a Rails initializer, application.rb, or environment config file:

~~~ruby 
SemanticLogger.add_appender(appender: :syslog)
~~~

**Comment by reidmorrison** [comment]
Documentation Updated
