### ISSUE TITLE
error with sentry appender

### ISSUE THREAD

**Issue by gingerlime** [rocketjob/semantic_logger#36]
I'm looking at moving from logging-rails + lograge to semantic logger. It looks great so far.

I'm trying to add the sentry appender. I added in my config:

```ruby
SemanticLogger.add_appender(:appender => :sentry, :level => :error)
```

When I log an error, I bump into this error:

```
2016-09-07 09:41:59.750979 E [11695:SemanticLogger::AppenderThread] SemanticLogger -- Appender thread: Failed to log to appender: #<SemanticLogger::Appender::Sentry:0x00000003b3f738 @formatter=#<SemanticLogger::Formatters::Raw:0x00000003b3cc68 @precision=6, @time_format="%Y-%m-%d %H:%M:%S.%6N", @log_host=true, @log_application=true>, @application=nil, @host=nil, @filter=nil, @name="SemanticLogger::Appender::Sentry", @level_index=4, @level=:error> -- Exception: NoMethodError: undefined method `user' for #<Hash:0x0000000287c718>
/usr/lib/ruby/gems/2.2.0/gems/sentry-raven-1.2.0/lib/raven/event.rb:63:in `initialize'
/usr/lib/ruby/gems/2.2.0/gems/sentry-raven-1.2.0/lib/raven/event.rb:102:in `new'
/usr/lib/ruby/gems/2.2.0/gems/sentry-raven-1.2.0/lib/raven/event.rb:102:in `from_message'
/usr/lib/ruby/gems/2.2.0/gems/sentry-raven-1.2.0/lib/raven/instance.rb:118:in `capture_type'
/usr/lib/ruby/gems/2.2.0/bundler/gems/semantic_logger-4278b62a1445/lib/semantic_logger/appender/sentry.rb:60:in `log'
/usr/lib/ruby/gems/2.2.0/bundler/gems/semantic_logger-4278b62a1445/lib/semantic_logger/logger.rb:191:in `block in appender_thread'
/usr/lib/ruby/gems/2.2.0/bundler/gems/semantic_logger-4278b62a1445/lib/semantic_logger/logger.rb:189:in `each'
/usr/lib/ruby/gems/2.2.0/bundler/gems/semantic_logger-4278b62a1445/lib/semantic_logger/logger.rb:189:in `appender_thread'
/usr/lib/ruby/gems/2.2.0/bundler/gems/semantic_logger-4278b62a1445/lib/semantic_logger/logger.rb:165:in `block in start_appender_thread'
```

Note that this log is from Sidekiq, since my sentry is set to report asynchronously.

If I manually report a message to sentry from within a Sidekiq job, it does work. e.g.

```ruby
class SomeWorker
  include Sidekiq::Worker
  def perform
    Raven.capture_message('this error goes to sentry')
    logger.error('this error does not')
  end
end
```

`logger.error` fails to report to sentry also if I call it outside the sidekiq job.

Any clues / tips on how to resolve this? did I set up something wrong?

**Comment by gingerlime** [comment]
If I comment out the [context](https://github.com/rocketjob/semantic_logger/blob/4278b62a1445899d2b59aec39e952280da0e9735/lib/semantic_logger/appender/sentry.rb#L57) from the message, then it seems to work.

**Comment by gingerlime** [comment]
@mhenrixon are you able to help?

**Comment by mhenrixon** [comment]
I'll dig into it sometime tonight

**Comment by gingerlime** [comment]
don't mean to nag, but did you have a chance to take a look, @mhenrixon ? I'm happy to submit a PR that removes this context, but maybe there's a better fix for this?

**Comment by reidmorrison** [comment]
@mhenrixon @gingerlime I need to publish a new gem version, should we wait for this to be resolved?

**Comment by gingerlime** [comment]
I would love to get feedback from @mhenrixon or anyone else who might know, but the fix on the PR was the only way I could get it to work with sentry. Having said that, we're still not using semantic logger yet in production (partly because we're waiting for this), so all my experience was based on fiddling around with this on my dev box.

**Comment by mhenrixon** [comment]
Let me have a look at it, I'll ping you in a few minutes.

**Comment by mhenrixon** [comment]
According to https://docs.sentry.io/clients/ruby/context/ @gingerlime's change is the right approach! 👍

**Comment by reidmorrison** [comment]
Thank you @gingerlime and @mhenrixon.
This will be included in the new gem that will be published shortly.

**Comment by gingerlime** [comment]
Great news! Thanks @mhenrixon and @reidmorrison for getting this merged.
