### ISSUE TITLE
Papertrail Appender

### ISSUE THREAD

**Issue by ervoiox** [rocketjob/semantic_logger#45]
Hi,

Does the syslog appender support TCP + TLS? There does not seem to be option to provide a certificate.

We use papertrail and it would be great if we could send our logs via the syslog appender via tls.

http://help.papertrailapp.com/kb/configuration/encrypting-remote-syslog-with-tls-ssl/

**Comment by reidmorrison** [comment]
Yes I believe it does, since it uses [Net::TCPClient](https://github.com/rocketjob/net_tcp_client/blob/master/lib/net/tcp_client/tcp_client.rb) under the covers which supports SSL.

The  config should be something like:
~~~ruby
{
  url: tcp://logger:8514, 
  tcp_client: {
    ssl: true
  }
}
~~~

The `tcp_client` option above can take a hash instead of `true` with the following keys:

Extract of the Net::TCPClient docs:
~~~
SSL Options
:ssl [true|false|Hash]
   true:  SSL is enabled using the SSL context defaults.
   false: SSL is not used.
   Hash:
     Keys from OpenSSL::SSL::SSLContext:
       ca_file, ca_path, cert, cert_store, ciphers, key, ssl_timeout, ssl_version
       verify_callback, verify_depth, verify_mode
     handshake_timeout: [Float]
       The number of seconds to timeout the SSL Handshake.
       Default: connect_timeout
   Default: false.
     See OpenSSL::SSL::SSLContext::DEFAULT_PARAMS for the defaults.
~~~

JSON logging over HTTPS is a better option instead of using the syslog format if paper trail supports it. Or maybe it supports TCP with SSL directly, with JSON formatted messages instead of the syslog format.

**Comment by ervoiox** [comment]
Hi, we will give this a try and report back!

**Comment by ervoiox** [comment]
Unfortunately it does not seem to work, we do not see the results in Papertrail, but the logs show the TCP client did connect:

```
2017-01-22 13:35:28.584243 I [32501:70305499164980] (121.7ms) Net::TCPClient -- Connected to logs.papertrailapp.com[ip]:port
2017-01-22 13:35:28.952904 I [32510:70305499164980] (112.9ms) Net::TCPClient -- Connected to logs.papertrailapp.com[ip]:port
2017-01-22 13:35:29.301239 I [32519:70305499164980] (116.5ms) Net::TCPClient -- Connected to logs.papertrailapp.com[ip]:port
```

Our config looked like this:

```ruby
# config/semantic_logger.rb

SemanticLogger.add_appender(
  appender: :syslog,
  url:      'tcp://papertrail:port',
  tcp_client: {
    ssl: {
       ca_file: "/path/to/papertrail-bundle.pem"
    }
  }
)
```

**Comment by ervoiox** [comment]
It isn't a big deal for us to continue to log to file and use papertrail's remote_syslog2 agent. You may close this issue if you prefer not to dig deeper. :smile:

**Comment by reidmorrison** [comment]
Can someone that uses papertrail create a pull request with a paper trail specific appender? Ideally avoiding the syslog appender so that all semantic log information is retained.

**Comment by joshkeys** [comment]
I don't believe Papertrail accepts logs over http/https only via syslog. I was able to get TLS TCP syslog working just fine with the following config. Very similar to @ervoiox.

```
config.semantic_logger.add_appender(
    appender: :syslog,
    url: 'tcp://something.papertrailapp.com:1234',
    tcp_client: {
      ssl: {
        ca_file: File.join(Rails.root, 'config', 'papertrail-bundle.pem')
      }
    }
  )
```

I don't know if a new appender is needed maybe just a documentation update once another person can verify.

Not sure if that location is the best place for the certificate file, but the config below works like a champ.

Only needed the following section from Papertrail's documentation. http://help.papertrailapp.com/kb/configuration/encrypting-remote-syslog-with-tls-ssl/

Rails 4.2.7.1
net_tcp_client 2.0.1
syslog_protocol 0.9.2
semantic_logger 4.0.0
rails_semantic_logger 4.0.1

**Comment by reidmorrison** [comment]
Thankyou @joshkeys, I added your example config above to the Appender documentation.

Please re-open this ticket if we need to re-consider a custom appender for Papertrail.
