### ISSUE TITLE
SemanticLogger.add_signal_handler is unusable

### ISSUE THREAD

**Issue by felixvf** [rocketjob/semantic_logger#49]
When `SemanticLogger.add_signal_handler` is called, the signal handler is installed. When the actual signal is sent and the signal handler is executed, the signal handler fails. It fails because it tries to autoload code. Autoloading code is not allowed during the execution of a signal handler.

## Testcase

```ruby

require 'semantic_logger'

SemanticLogger.add_signal_handler

our_pid = Process.pid

Process.kill("TTIN",our_pid)
```

### Expected result

A stack trace should be printed.

### Actual result

A ThreadError `can't be called from trap context` is raised and printed.

## Additional comments

This bug can be easily obscured by using other features of semantic_logger before the signal handler is executed, as the other features may also trigger autoloading, which succeeds in this case and thus will not be performed again when the signal handler is finally executed. Hence, in these cases, the bug will not be revealed.

## Solution idea

Preload all code (use `require` instead of `autoload`), at least when `SemanticLogger.add_signal_handler` is called.

**Comment by reidmorrison** [comment]
The following works:

~~~ruby
require 'semantic_logger'

SemanticLogger['hello']
SemanticLogger.add_signal_handler

our_pid = Process.pid

Process.kill("TTIN",our_pid)
~~~

Does not make any sense to add a signal handler but then not create any loggers.

**Comment by reidmorrison** [comment]
This is a limitation of Ruby MRI. JRuby works fine with the original code above.
