### ISSUE TITLE
Appender thread: Failed to log to appender: nil (passenger + rails_semantic_logger)

### ISSUE THREAD

**Issue by jalberto** [rocketjob/semantic_logger#54]
Appender thread: Failed to log to appender: nil -- Exception: NoMethodError: undefined method `log' for nil:NilClass
    [167:SemanticLogger::AppenderThread] SemanticLogger -- Appender thread: Failed to flush appender: nil -- Exception: NoMethodError: undefined method `name' for nil:NilClass

**Comment by reidmorrison** [comment]
When using Passenger, additional configuration is required: https://rocketjob.github.io/semantic_logger/forking.html

**Comment by jalberto** [comment]
@reidmorrison I am using rails_semantic_logger, as I understand the gem take care of Passenger compatibility

**Comment by reidmorrison** [comment]
If you were able to get Passenger working please post the details here so that anyone else using Passenger can get the fix.

**Comment by jalberto** [comment]
@reidmorrison the only way to make it work is to have only one appender

**Comment by reidmorrison** [comment]
Ah, ok. So it does work for the file appender.

Not all appenders implemented `#reopen`. You could try implementing `#reopen` for whatever other appender you are trying to use.

**Comment by jalberto** [comment]
I am trying to use stdour appender, to run in docker

**Comment by reidmorrison** [comment]
We have made changes to Rails Semantic Logger to better support the console logging option. Can you try the latest version.

Also turn off Rails Server console logging to avoid issues. For example with Puma you can use the `--quiet` option, not sure what the same option is under passenger. Then the logging can be properly controlled via the appender options in Rails Semantic Logger.

**Comment by letavi** [comment]
Hmm, what is the best solution for this issue? I use rails_semantic_logger gem and gelf gem for Graylog. But I also meet this issue. "Failed to log to appender: Exception: NoMethodError: undefined method `message' for nil:NilClass".
