### ISSUE TITLE
some bug about SemanticLogger::Loggable

### ISSUE THREAD

**Issue by jonydev** [rocketjob/semantic_logger#60]
Hi, I'm using SemanticLogger now in my project, I use SemanticLogger::Loggable to write log in each class, but I found that, if I write log in method B of module A, as I include SemanticLogger::Loggable, the log run success, but when another class C include module A, and call method B, there is error that the logger method not in class C.    
I think the reason is module B include SemanticLogger::Loggable, so module B has extend a method of logger, but if class C include module B, class C doesn't have method logger because C didn't include SemanticLogger::Loggable.    
I saw the source of Loggable, I think it's hard to slove this problem.

**Comment by reidmorrison** [comment]
Can you supply a standalone code example that reproduces the issue you are experiencing?

**Comment by reidmorrison** [comment]
Sounds like the same issue as https://github.com/rocketjob/semantic_logger/issues/76.

Recommend using the sample code there instead of using `SemanticLogger::Loggable`
