### ISSUE TITLE
missing logs when running in multiple docker

### ISSUE THREAD

**Issue by jalberto** [rocketjob/semantic_logger#61]
configuring stdout appender and running 2 dockers, one for main rails other for sidekiq, only rails logs are being logged, sidekiq logs are lost.
It works as expected when running both proccesses in local dev environment

**Comment by reidmorrison** [comment]
We don't use Sidekiq anymore, we only run [Rocket Job](http://rocketjob.io), so don't know how to help you there. Sounds it works fine with Rails, you should look into the way Sidekiq is booting your Rails environment inside the docker container.

**Comment by jalberto** [comment]
Seems not related to sidekiq itself, as it works with lograge to plain Rail slogger

**Comment by brhenrique** [comment]
I'm having the same issue. In my case, logs from Sidekiq are written to the file, but are not sent to STDOUT.

**Comment by reidmorrison** [comment]
Ok, that makes sense. With Rails, the Rails Semantic Logger gem patches the Server code to add stdout logging when it creates the stdout logger: https://github.com/rocketjob/rails_semantic_logger/blob/master/lib/rails_semantic_logger/extensions/rails/server.rb

Sounds like a similar patch would be required for Sidekiq. Or try adding a stdout logger in an initializer when Sidekiq is started. Just be sure it does not add the extra stdout appender when running inside of a Rails server.

Someone mentioned that they were going to look into creating a gem to patch Sidekiq the same way Rails Semantic Logger patches Rails, something like `sidekiq_semantic_logger`.

**Comment by brhenrique** [comment]
Thanks, you're right. Adding this to `config/environments/development.rb` was enough to make it work.

```
if Sidekiq.server?
  Sidekiq::Logging.instance_eval do
    def logger
      SemanticLogger.add_appender(io: $stdout, formatter: :color)      
    end
  end
end
```

**Comment by reidmorrison** [comment]
Adding this setting to `config/environments/development.rb` should also work.

~~~ruby
# Add a stdout logger when running Sidekiq.
config.semantic_logger.add_appender(io: $stdout, formatter: :color) if Sidekiq.server?
~~~
