### ISSUE TITLE
version 4.0 break hash syntax

### ISSUE THREAD

**Issue by jalberto** [rocketjob/semantic_logger#62]
logger.debug foo: 'foo', bar: 'bar'
    ArgumentError: unknown keywords: foo, bar

This was working in 3.4

**Comment by reidmorrison** [comment]
Correct, as mentioned in the v4 upgrade notes. This was a community requested change that was held off until v4 since it is not backward compatible: https://github.com/rocketjob/semantic_logger/issues/35
