### ISSUE TITLE
not logging authenticated controllers

### ISSUE THREAD

**Issue by jalberto** [rocketjob/semantic_logger#63]
I am using knock for authentication, rails_semantic_controller is loging by default any controller that skips authentication, but is ignoring authenticated controllers

**Comment by reidmorrison** [comment]
Suggest you look into whether knock is patching the Rails logging system. It could be overriding a patch that Rails SemanticLogger applies.

**Comment by jalberto** [comment]
Any clue @reidmorrison ? I cannot see any reference in Knock related to logging (with lograge works)

**Comment by reidmorrison** [comment]
Semantic Logger only logs what it is given. If knock is choosing what to log, there is nothing Semantic Logger can do about it.

**Comment by jalberto** [comment]
I cannot find any clue in knock's code that could hijack the logging system

**Comment by mathiasAichinger** [comment]
@jalberto I'm also using knock and I have no problems. Everything is logged as it should be.

**Comment by jalberto** [comment]
I didn't tested new version, thanks!
