### ISSUE TITLE
sentry appender potential error

### ISSUE THREAD

**Issue by gingerlime** [rocketjob/semantic_logger#74]
There seems to be a small problem with the sentry appender when it uses `capture_exception`

See https://github.com/getsentry/raven-ruby/issues/678

I suspect that the `context` isn't passed correctly and should be set inside the `extra` key. It's just a suspicion at this stage, I didn't get a chance to dig deeper... I'll try to play around and maybe submit a PR, but I'm going on holiday soon, so not sure when I'll have a chance to look into it.

**Comment by nateberkopec** [comment]
Needs a full stacktrace posted.

**Comment by gingerlime** [comment]
Hey @nateberkopec @reidmorrison. Sorry, I completely forgot about this (holiday effect I guess).

I think I know where the problem is, but didn't get a chance to test it yet

If you look [here](https://github.com/rocketjob/semantic_logger/blob/master/lib/semantic_logger/appender/sentry.rb#L54-L59), the context is being munged to fit with the raven structure (that was part of the fix I applied on #70).

What I missed however, is doing the same thing [when an exception is raised](https://github.com/rocketjob/semantic_logger/blob/master/lib/semantic_logger/appender/sentry.rb#L50-L52) just a few lines above it.

Hope to find time to test and apply this fix over the weekend hopefully.

**Comment by gingerlime** [comment]
@reidmorrison created a PR that should fix this. Since the tests are rather synthetic, I'm wondering how to simulate this on a "real" environment though... Any pointers?

**Comment by reidmorrison** [comment]
@gingerlime check out this test for an example on how to use both mocks during tests and then to actually call the target system on demand for "real" development testing: https://github.com/rocketjob/semantic_logger/blob/master/test/metric/signalfx_test.rb#L13

It does it by means of an environment variable so that testing in Travis is mocked.

**Comment by gingerlime** [comment]
Thanks @reidmorrison. That's a good suggestion.

I'm still curious to understand when this branch of the appender is activated though? (When does log.exception get set).

**Comment by reidmorrison** [comment]
How about we do a screen sharing session and walk through the code?
I am available 10am through 5 pm Eastern (NY) time, send me a private message through Github with a time and I will send you link to chat.

**Comment by gingerlime** [comment]
Thanks @reidmorrison, that's exceptionally kind of you. Totally awesome... I really don't want to take up your time though (and it's also pretty busy here, to be perfectly honest).

I hope to find some time to play around with it a bit more over the weekend, and hope to figure things out. Hope to keep the option for a screenshare open for future though? I'm sure something or other will come up, and I'd love the opportunity, but best to keep it for something more important.

Cheers,
Yoav
