### ISSUE TITLE
How to design a new SemanticLogger::Loggable

### ISSUE THREAD

**Issue by lonre** [rocketjob/semantic_logger#76]
```ruby
module Foo
  include SemanticLogger::Loggable

  def foo
    logger.info 'foo in Foo'
  end
end


class Bar
  include Foo

  def bar
    foo
  end
end
```

`Bar.new.bar` will throw `NoMethodError: undefined method 'logger' for Bar:Class`

I have some cases like this, `Bar` does not care about `logger`, it just do a method call.

Any suggest about this case? or design a new `SemanticLogger::Loggable`? Thanks

**Comment by reidmorrison** [comment]
Unfortunately the current design is required to get it to work with Rails. The above code will fix the issue, instead of using `SemanticLogger::Loggable`
