### ISSUE TITLE
Prettify stacktrace on exceptions / 404

### ISSUE THREAD

**Issue by Silex** [rocketjob/semantic_logger#79]
Hello,

What is the rationale of semantic_logger reguarding 404 or exceptions?

Right now it looks like the error _is_ captured by semantic_logger (good!), but then the stack trace is blurted out like normal.

Is there a way to "jsonize" / prettify / suppress the stack trace?
Or maybe simply store it as is but in another log?

I'd really like to have "one line = one request" in the log for easier reading of what happened.

For information, I'm trying to find a replacement for lograge (see https://github.com/roidrage/lograge/issues/48)

**Comment by reidmorrison** [comment]
This is a very interesting idea, sounds like we should create a custom formatter that ensures that only one line is output at a time. For example, it would reduce the exception to just the message and leave out the backtrace.

Is optionally colorizing the single line output useful?

In addition to the one liner log file above, to add a JSON log file, for consumption by ELK, Splunk, etc.:

~~~ruby
config.semantic_logger.add_appender(file: "log/#{Rails.env}.json", formatter: :json)
~~~

**Comment by Silex** [comment]
Well, for me colorizing the line would not be very useful.

Right now I'm switching gears and playing with the elasticsearch appender, I see that the exception is correctly forwarded there, so it looks good!

Anyway, I guess I'll have two appenders:
- file (log/production.log) for classic logs where I'd want to remove the stacktrace for simpler reading of the logs (as you said the message can be useful tho)
- elasticsearch with full verbosity of the errors.

While I have your attention, I have trouble finding how to add custom informations to each requests. I know about `config.log_tags` where I could add informations from the request, but how do I access controller methods like `current_user`? Should I add an around filter to each requests that adds the information I need to the request object?

**Comment by reidmorrison** [comment]
I really like elasticsearch for centralized logging, it is a great tool for that purpose.

Yes, it sounds like an around filter is the way to go for adding named tags around all logging within a controller. Unfortunately such tagged logging only applies to logging within the controller and would not affect any logging at the Rack level.

If using a cookie store, another option could be to grab the user_id from the session cookie directly as part of processing in `config.log_tags`. That way the tags would be present during Rack logging.

**Comment by Silex** [comment]
I discovered something event simpler:

``` ruby
  # ApplicationController
  def append_info_to_payload(payload)
    super
    payload[:user]    = { id: current_user&.id, agent: request.user_agent }
    payload[:cookies] = request.cookies rescue nil
  end
```
That way the information is part of the payload. Do you see any downside to this?

**Comment by Silex** [comment]
Ok, FYI here is what works all the time:

``` ruby
Rails.application.config.log_tags = {
  ip: :remote_ip,
  agent: :user_agent,
  user_id: ->(request) {
    begin
      session_key = Rails.application.config.session_options[:key]
      session_data = request.cookie_jar.encrypted[session_key]
      warden_data = session_data["warden.user.user.key"]
      warden_data[0][0]
    rescue
      nil
    end
  }
}
```

**Comment by reidmorrison** [comment]
To create a custom formatter, in this case a one line output format, create the following file in the codebase:

~~~ruby
class OneLineFormatter < SemanticLogger::Formatters::Default
  def message
    "-- #{log.message.gsub("\n", '')}" if log.message
  end

  def exception
    "-- Exception: #{log.exception.class}: #{log.exception.message.gsub("\n", '')}" if log.exception
  end
end
~~~

Then in the rails config file tell it to use the one line formatter:
~~~ruby
config.rails_semantic_logger.format = OneLineFormatter.new
~~~

**Comment by Silex** [comment]
Oh neat! Looks like we can close this issue then. I'll run some tests.

Btw, I noticed on https://rocketjob.github.io/semantic_logger/rails.html that sometimes it is `config.rails_semantic_logger` and sometimes `config.semantic_logger`. Is this intentionnal?

**Comment by Silex** [comment]
All clear, thanks a lot!

**Comment by Silex** [comment]
Shall we close this or do you keep it as a remainder to update documentation?

**Comment by reidmorrison** [comment]
Thank you for the idea and verifying the code. Published the :one_line formatter

**Comment by Silex** [comment]
:+1:
