### ISSUE TITLE
Exception when trying to pass a block containing a hash without message

### ISSUE THREAD

**Issue by yboulkaid** [rocketjob/semantic_logger#86]
Hi,
I'm trying to use a logger with no message, only a block.
This is perfectly supported, unless the content of the block is a `Hash`. semantic_logger then [tries to parse it into params](https://github.com/rocketjob/semantic_logger/blob/97247126de32e6ecbf74cbccaa3b3732768d52c5/lib/semantic_logger/log.rb#L151-L152) and the logging fails.

```ruby
logger.info { Hash(meta: 'data') }
=> ArgumentError: unknown keyword: meta
from [...]/semantic_logger-4.2.0/lib/semantic_logger/log.rb:71:in `assign'
```

When appending `to_s` to the hash it works perfectly.

One solution would be to assign the result of the block directly to the `message` instead of trying to parse it. Not sure if that would break any of the gem internals though..

Running on ruby 2.3, semantic_logger 4.2.0, on Rails 5.1

**Comment by reidmorrison** [comment]
https://github.com/rocketjob/semantic_logger/pull/100 will fix this issue, should have a new gem out shortly. Thank you for your patience.
