### ISSUE TITLE
Undefined Method: SemanticLogger.on_metric

### ISSUE THREAD

**Issue by m-kind** [rocketjob/semantic_logger#93]
### Environment
* Ruby 2.3.1
* Semantic Logger 4.2.0

### Description

This is basically the minimum amount code required to reproduce the problem on the console. Following the example in the _Guide_ (section _ Custom Subscriber_):

```
require 'semantic_logger'
SemanticLogger.on_metric do |log_struct|
  puts "Metric: #{log_struct.metric} with duration: #{log_struct.duration}ms"
end
```
I get the following error:

```
NoMethodError: undefined method `on_metric' for SemanticLogger:Module
```

When searching for `on_metric` in the `semantic_logger` codebase (and also `rails_semantic_logger`) I only got results in the CHANGELOG.md. 

I have no idea what I could potentially have done wrong. What is the reason for `on_metric` being undefined?

**Comment by jgaviria** [comment]
It seems that the on_metric method has been deprecated.

**Comment by m-kind** [comment]
Yes, but it looks more like it has been silently removed - could not find any hint in the changelog and it's still present in the documentation. So finally I ended up writing my own subscriber for InfluxDB.

**Comment by Draiken** [comment]
Why is this closed? All the docs still reference a method that no longer exists. There's no specification on how to do the same thing without that method.

Could we reopen this until we fix all that?

**Comment by m-kind** [comment]
@Draiken: You're absolutely right - I have no idea why I closed it and it makes sense to keep it open...

**Comment by reidmorrison** [comment]
The method `#on_metric` is no longer available and all log events flow through the same `#on_log` callback handlers. The documentation was only recently fixed.
