### ISSUE TITLE
ArgumentError: wrong number of arguments (given 1, expected 0) for  semantic_logger/log.rb:71:in `assign'

### ISSUE THREAD

**Issue by fanantoxa** [rocketjob/semantic_logger#99]
Reopend https://github.com/rocketjob/semantic_logger/issues/77

Environment
ruby 2.3.1
Puma, Rails
Rails Semantic Logger Version: last
No additional rails configuration

Bug in the code,
@reidmorrison  Hi. How to reopen this bug? still happening.
Problem a bit different:
So CORS gem doing next:
They call debug with a block
```
debug(env) do
  add_headers.each_pair do |key, value|
    if headers.has_key?(key)
      headers["X-Rack-CORS-Original-#{key}"] = value
    end
  end
end
```
And this code return the Hash but with a String keys (Usual header pairs)
So this block go through log_internal to https://github.com/rocketjob/semantic_logger/blob/master/lib/semantic_logger/log.rb#L148

And here it doing:
```
if block_given? && (result = yield)
  if result.is_a?(String)
    message = message.nil? ? result : "#{message} -- #{result}"
    assign(message: message, payload: payload, exception: exception)
  elsif message.nil? && result.is_a?(Hash)
    assign(result)
```
So here the `message` is `nil` and result is a `Hash`
But `Hash` with `string` keys.
So it call `assign(result)`
Which accept only symbol keys:
```
def assign(message: nil,
               payload: nil,
               min_duration: 0.0,
               exception: nil,
               metric: nil,
               metric_amount: nil,
               duration: nil,
               backtrace: nil,
               log_exception: :full,
               on_exception_level: nil,
               dimensions: nil)
```
So I'm getting
```
#<ArgumentError: wrong number of arguments (given 1, expected 0)>
/app/vendor/bundle/ruby/2.3.0/gems/semantic_logger-4.2.0/lib/semantic_logger/log.rb:71:in `assign'
```

**Comment by reidmorrison** [comment]
Thank you for isolating this one, your PR https://github.com/rocketjob/semantic_logger/pull/100 is most welcome and should help significantly with this ongoing issue.

**Comment by reidmorrison** [comment]
Thank you for the pull request
